// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-S_ngfbTqQ7okcim62iPVhbVIA6TYKNM',
    appId: '1:650533910297:web:b5f37f040829516450f788',
    messagingSenderId: '650533910297',
    projectId: 'bari-bodol-cbb21',
    authDomain: 'bari-bodol-cbb21.firebaseapp.com',
    storageBucket: 'bari-bodol-cbb21.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGRiYJi_g0CMhdfD24dxyvhT_mr332jYE',
    appId: '1:650533910297:android:b2491e0e6681708b50f788',
    messagingSenderId: '650533910297',
    projectId: 'bari-bodol-cbb21',
    storageBucket: 'bari-bodol-cbb21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5R0HxxIWwlNLXX9CQpLrSlbZEvH7A1sU',
    appId: '1:650533910297:ios:338dea7bfedd207b50f788',
    messagingSenderId: '650533910297',
    projectId: 'bari-bodol-cbb21',
    storageBucket: 'bari-bodol-cbb21.appspot.com',
    iosBundleId: 'com.example.bariBodol',
  );
}
